In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
from google.colab import files
uploads=files.upload()

Saving Nairobi Office Price Ex.csv to Nairobi Office Price Ex.csv

In [3]:
data=pd.read_csv('Nairobi Office Price Ex.csv')

In [4]:
data.head(2)

        LOC  FUR          AMB PROX_SCH  ... WATER HK_SER       SIZE      PRICE
0     karen  yes       serene       no  ...   yes    yes  32.502345  31.707006
1  madaraka  yes  semi_serene      yes  ...    no     no  53.426804  68.777596

[2 rows x 10 columns]

In [15]:
nominal=['LOC','FUR','WATER','HK_SER']
ordinal=['AMB','PROX_SCH','PROX_ROAD','PROX_MALL']
numerical=['SIZE']
target=['PRICE']

for feature in ordinal:
  value=data[feature]
  encoder=LabelEncoder()
  trans_f=encoder.fit_transform(value)
  data[feature]=trans_f

In [10]:
data
#data[nominal]-will slice the table only present the nominal data 
#data['FUR']

         LOC  FUR  AMB  PROX_SCH  ...  WATER  HK_SER       SIZE      PRICE
0      karen  yes    2         0  ...    yes     yes  32.502345  31.707006
1   madaraka  yes    1         1  ...     no      no  53.426804  68.777596
2      karen   no    0         0  ...    yes     yes  61.530358  62.562382
3      karen  yes    1         0  ...    yes     yes  47.475640  71.546632
4   buruburu   no    1         0  ...    yes     yes  59.813208  87.230925
5    donholm   no    2         0  ...     no     yes  55.142188  78.211518
6    langata   no    3         1  ...     no     yes  52.211797  79.641973
7    langata  yes    2         0  ...    yes      no  39.299567  59.171489
8    donholm  yes    1         1  ...    yes      no  48.105042  75.331242
9      karen  yes    2         0  ...     no      no  52.550014  71.300880
10  madaraka  yes    0         1  ...    yes     yes  45.419730  55.165677
11   langata   no    1         1  ...    yes     yes  54.351635  82.478847
12  buruburu  yes    1         1  ...     no      no  44.164049  62.008923
13     karen  yes    1         1  ...    yes     yes  58.168471  75.392870

[14 rows x 10 columns]

In [16]:
new_data=pd.get_dummies(data[nominal])

In [17]:
new_data

    LOC_buruburu  LOC_donholm  LOC_karen  ...  WATER_yes  HK_SER_no  HK_SER_yes
0              0            0          1  ...          1          0           1
1              0            0          0  ...          0          1           0
2              0            0          1  ...          1          0           1
3              0            0          1  ...          1          0           1
4              1            0          0  ...          1          0           1
5              0            1          0  ...          0          0           1
6              0            0          0  ...          0          0           1
7              0            0          0  ...          1          1           0
8              0            1          0  ...          1          1           0
9              0            0          1  ...          0          1           0
10             0            0          0  ...          1          0           1
11             0            0          0  ...          1          0           1
12             1            0          0  ...          0          1           0
13             0            0          1  ...          1          0           1

[14 rows x 11 columns]

In [19]:
#Join the new data and data table/data frame
#axis=1 shows we are concatinating on a given column
#axis=0 shows we are concatinating on a given rows
#drop the nominals to remain with the hot encoding
final_data=pd.concat([new_data,data],axis=1)
final_data.drop(nominal,axis=1,inplace=True)

In [21]:
final_data.head(3)

   LOC_buruburu  LOC_donholm  LOC_karen  ...  PROX_MALL       SIZE      PRICE
0             0            0          1  ...          1  32.502345  31.707006
1             0            0          0  ...          1  53.426804  68.777596
2             0            0          1  ...          1  61.530358  62.562382

[3 rows x 17 columns]